// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmXEm55dZ6LolnkmhdBCDSsZlIaUqCeaY',
    appId: '1:579051887787:android:47b3a3c28faa5c8b356bee',
    messagingSenderId: '579051887787',
    projectId: 'attorney-e5f09',
    storageBucket: 'attorney-e5f09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHHubxgoUojBJ0gv9ct3MXZW7wg-CtSrk',
    appId: '1:579051887787:ios:ed81017f9eb86d09356bee',
    messagingSenderId: '579051887787',
    projectId: 'attorney-e5f09',
    storageBucket: 'attorney-e5f09.firebasestorage.app',
    androidClientId: '579051887787-0dd4jv4ftd7f1jvvqb0m8uvqb0mct8to.apps.googleusercontent.com',
    iosClientId: '579051887787-4va0bekvhq6lldbksrrjvrbbledkqihi.apps.googleusercontent.com',
    iosBundleId: 'com.attorney.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1a7PI1PyMYgxdsb6IY-rKPndehqIKHzc',
    appId: '1:579051887787:web:5c3fd8a89909995c356bee',
    messagingSenderId: '579051887787',
    projectId: 'attorney-e5f09',
    authDomain: 'attorney-e5f09.firebaseapp.com',
    storageBucket: 'attorney-e5f09.firebasestorage.app',
    measurementId: 'G-6VPXB5NE9K',
  );

}